FROM drogonframework/drogon

LABEL description="Drogon Subdirectory"

RUN apt-get update && apt -y upgrade
RUN apt-get install -y mariadb-server

RUN mkdir -p /home/drogon_subdirectory && \
	cd /home/drogon_subdirectory && \
	drogon_ctl create project http_server

COPY .gitignore build.sh CMakeLists.txt main.cpp README /home/drogon_subdirectory/
COPY http_server/ /home/drogon_subdirectory/http_server

WORKDIR /home/drogon_subdirectory

CMD /usr/bin/mysqld_safe --user=mysql &

EXPOSE 80 3306